#!/bin/bash

gitpackagepath="/opt/gitpackages/"

if [ -d "$gitpackagepath" ]
then
	for i in $(ls -d "$gitpackagepath"*)
	do
		if [ -d "$i" ]
		then
			echo "Updating $i"
			git -C "$i" pull
		fi
	done
else
	echo "$gitpackagepath does not exist"
fi
