#!/bin/bash

scriptname="gitupdate"
packagename="gitupdater"
gitpackagepath="/opt/gitpackages/"

if [[ $EUID -ne 0 ]]
then
   echo "$scriptname must be run as root"
else
	if [ -d "$gitpackagepath" ]
	then
		for i in $(ls -d "$gitpackagepath"*)
		do
			if [ -d "$i" ]
			then
				echo "Updating $i"
				git -C "$i" pull
			fi
		done
	else
		echo "$gitpackagepath does not exist"
		echo "Please reinstall $packagename"
	fi
fi
